GET http://localhost:3001/notes/

###
DELETE http://localhost:3001/notes/1
###
POST http://localhost:3001/api/notes/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlamZlbGxvdyIsImlkIjoxLCJpYXQiOjE2NjI2NTcyMDN9.xbWdwpRSCeTmmJEtz1bbH0MM02K5Frf02tKeCwRJYdE

{
    "content": "another note 4",
    "important": true
}

###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "third",
    "name": "tej fellow",
    "disabled": false
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "secondUser",
    "password": "secret"
}
###
PUT http://localhost:3001/api/users/secondUser
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlamZlbGxvdyIsImlkIjoxLCJpYXQiOjE2NjI2NTg3NTZ9.OcKDVcCbhfgVSUYs-BFP-T3dy3qos8iN5iJnUO5Wg_8

{
    "disabled": false
}