GET http://localhost:3001/notes/

###
DELETE http://localhost:3001/notes/1
###
POST http://localhost:3001/api/notes/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlaiIsImlkIjoxLCJpYXQiOjE2NjI2OTY1MzN9.vqpXShInLf7DQx0tZ0iyfkwFXLbVf2AoaRa50SEP_Q8

{
    "content": "another note 4",
    "important": false
}

###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "sixth",
    "name": "tej fellow",
    "disabled": true
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "tej",
    "password": "secret"
}
###
PUT http://localhost:3001/api/users/third
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlaiIsImlkIjoxLCJpYXQiOjE2NjI2OTc4MzV9.y8CfYgG7a7l4rrxsTrecKpr1x_OIRtatkJwBaTZXGKc

{
    "disabled": true
}